# Generated by Django 5.2.5 on 2025-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='India', max_length=100)),
                ('indicator', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
